on:
  workflow_dispatch:

name: Build Flask Application

jobs:
  build_container:
    name: Create Credentials
    runs-on: ubuntu-latest
    environment: sandbox
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure Azure Credentials
      uses: azure/docker-login@v1
      with:
        login-server: ${{secrets.REGISTRY_NAME}}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
      env:
        ACR_REGISTRY: ${{secrets.REGISTRY_NAME}}
        ACR_REPOSITORY: 1bvssandbox
        IMAGE_TAG: latest
      run: |
        docker build -t $ACR_REGISTRY/$ACR_REPOSITORY:$IMAGE_TAG .
        docker push $ACR_REGISTRY/$ACR_REPOSITORY:$IMAGE_TAG
